### PR TITLE
Technical Specification

### PR DESCRIPTION
**Pull request by Amakran2003**
Technical specification of the Sportshield project by Team 3.

### CODE REVIEW

**Review by T3rryc — CHANGES_REQUESTED** [review]
creds.txt remove and single dash on line 115

**Review by GuillaumeDespaux — CHANGES_REQUESTED** [review]
You can add the little ✅ in the technical specification in front of my name, also remove the creds.txt file

**Review by GuillaumeDespaux — APPROVED** [review]
Perfect for me 👌

**Review by T3rryc — CHANGES_REQUESTED** [review]
line 115 , single dash

**Review by T3rryc — APPROVED** [review]

**Pull request merged**
